spring.application.name=campaignx-agent

campaignx.api.base-url=https://campaignx.inxiteout.ai/api/v1
campaignx.api.key=YOUR_CAMPAIGNX_API_KEY

openrouter.api.key=YOUR_OPENROUTER_API_KEY
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.model=meta-llama/llama-3-8b-instruct