spring.application.name=campaignx-agent

campaignx.api.base-url=https://campaignx.inxiteout.ai/api/v1
campaignx.api.key=BmtWNa_EGZL_OG6117tjXFq89-1KrfXkSnQzCtjrq_o

openrouter.api.key=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
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.model=meta-llama/llama-3-8b-instruct